cmap ;kek /home/solomos/mm/kek
cmap ;kel /home/solomos/mm/kel
cmap ;b /home/solomos/mm/Metastasis/Standalone
cmap ;y /home/solomos/mm/gds/Yugioh
cmap ;cac /home/solomos/.cache
cmap ;cf /home/solomos/.config
cmap ;D /home/solomos/Downloads
cmap ;d /home/solomos/Documents
cmap ;dt /home/solomos/.local/share
cmap ;rr /home/solomos/.local/src
cmap ;h /home/solomos
cmap ;m /home/solomos/Music
cmap ;lb /home/solomos/.local/bin
cmap ;lsr /home/solomos/.local/src
cmap ;lsh /home/solomos/.local/share
cmap ;vv /home/solomos/Videos
cmap ;help /home/solomos/mm/Linux-Guides
cmap ;ilb /home/solomos/ArchArchitectureProjects/Ilbal/Videogame
cmap ;th /home/solomos/THICC
cmap ;tv /home/solomos/THICC/Videos
cmap ;tu /home/solomos/THICC/UNSEEN_FOR_YEARS
cmap ;tx /home/solomos/mm/TextFiles
cmap ;a /home/solomos/mm/ArchArchitectureProjects
cmap ;lg /home/solomos/mm/Linux-Guides
cmap ;gp /home/solomos/mm/Godot/Projects
cmap ;ge /home/solomos/mm/Godot/Engines
cmap ;gy /home/solomos/mm/Godot/Projects/Yugioh/1ShadowDuels
cmap ;gd /home/solomos/mm/gds
cmap ;bf /home/solomos/.config/shell/bm-files
cmap ;bd /home/solomos/.config/shell/bm-dirs
cmap ;cfx /home/solomos/.config/x11/xresources
cmap ;cfdb ~/.local/src/dwmblocks/config.h
cmap ;cfdw ~/.local/src/dwm/config.h
cmap ;Ln /home/solomos/mm/Linux-Guides/NOTES.txt
cmap ;Lt /home/solomos/mm/Linux-Guides/tar.txt
cmap ;Lf /home/solomos/mm/Linux-Guides/common-ffmpeg-commands.txt
cmap ;Bm /home/solomos/mm/Metastasis/Standalone/Check_these!.txt
cmap ;Bc /home/solomos/mm/Metastasis/Standalone/Core_GDD_that_needs_cleanup.txt
cmap ;Bg /home/solomos/mm/Metastasis/Standalone/Game
cmap ;Ya /home/solomos/mm/gds/Yugioh/1SRPG/TXT/amain-nostalgia.txt
cmap ;Yo /home/solomos/mm/gds/Yugioh/1SRPG/TXT/BEYOND_SEQUEL_Grand_Campaign_Online.txt
cmap ;Ys /home/solomos/mm/gds/Yugioh/1SRPG/TXT/TRPG_The_Pyramid_of_the_Sun_God.txt
cmap ;Ma /home/solomos/mm/gds/The_Mathemagician/The_Mathemagician_v9plus.txt
cmap ;K /home/solomos/mm/gds/Kallipolis/GDD.txt
cmap ;Lg /home/solomos/mm/gds/The_Labyrinth_of_Endless_Sin_-_Dungeon_Crawler_Multiplayer/GDD.txt
cmap ;Ll /home/solomos/mm/gds/The_Labyrinth_of_Endless_Sin_-_Dungeon_Crawler_Multiplayer/Lore_books_to_spread_around-eg_origin_of_cancer_and_worms.txt
cmap ;Q /home/solomos/mm/gds/Gamer_Quiz-Buzz_Free_Mod_Centric/GDD.txt
cmap ;Ba /home/solomos/mm/ArchArchitectureProjects/BraveNewAlexandria/AncientGreekUtopia.txt
cmap ;Ea /home/solomos/mm/Eselegia/AshenKeepersOfKnowledge/KnowledgeBook_AshenKeepersofKnowledge.txt
cmap ;Eg /home/solomos/mm/Eselegia/Book2_ThyGoldBlood.txt
cmap ;Il /home/solomos/mm/ArchArchitectureProjects/Illuminopolis/Illuminopolis.txt
cmap ;2084 /home/solomos/mm/ArchArchitectureProjects/2084_TheCityUponTheHill/ideal_utopia_2084.txt
cmap ;Li /home/solomos/mm/ArchArchitectureProjects/YoutubeVids/ListOfMiscIdeas.txt
cmap ;Mi /home/solomos/mm/TextFiles/misc.txt
cmap ;Mwh /home/solomos/mm/TextFiles/whbooks.txt
cmap ;PP /home/solomos/mm/TextFiles/PP.txt
cmap ;cfv /home/solomos/.config/nvim/init.vim
cmap ;cfz /home/solomos/.config/zsh/.zshrc
cmap ;cfa /home/solomos/.config/shell/aliasrc
cmap ;cfp /home/solomos/.config/shell/profile
cmap ;cfm /home/solomos/.config/mutt/muttrc
cmap ;cfn /home/solomos/.config/newsboat/config
cmap ;cfu /home/solomos/.config/newsboat/urls
cmap ;cfmb /home/solomos/.config/ncmpcpp/bindings
cmap ;cfmc /home/solomos/.config/ncmpcpp/config
cmap ;clf /home/solomos/.config/lf/lfrc
cmap ;clF /home/solomos/.config/lf/scope
cmap ;cfX /home/solomos/.config/nsxiv/exec/key-handler
cmap ;cfs /home/solomos/local/bin/shortcuts
